services:
  - type: web
    name: spendsmart
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python
    region: oregon
    plan: free
